version: '3.8'

services:
  serving-api:
    container_name: serving-api
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../data:/app/data
      - ../artifacts:/app/artifacts
    ports:
      - "8080:8080"
    environment:
      - N8N_WEBHOOK_URL=http://n8n:5678/webhook/explain-score
    networks:
      - shared_network

networks:
  shared_network:
    name: mon_reseau_projet
    driver: bridge